### PR TITLE
Add Wagtail 2.x / Django 2.x support

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Comment by tomdyson** [comment]
Any ideas about the failing tests? I would be happy to drop Wagtail <2 support.

**Comment by gasman** [comment]
@tomdyson Fixed in the latest commit - was due to typos in the Travis config, and older versions of Django needing a pinned version of django-rest-framework.

**Comment by narnikgamarnikus** [comment]
When do you plan to take PR?

**Comment by alanmoo** [comment]
We're getting to a spot where we'd love to start integrating this into our Wagtail instance. Is there anything that my team can help with to get this landed?

**Comment by tomdyson** [comment]
Hi @alanmoo, we're planning to give this app some more attention over the next few weeks. In the meantime, if you have any time to test @gasman's [branch](https://github.com/gasman/wagtail-experiments/tree/admin/wagtail-2.0) on your instance, and report back, that would be very helpful.

**Comment by AimeeMS** [comment]
Has there been any update on this support update?

**Pull request merged**
